name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Build with Gradle
      run: gradle build

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: build/libs/sample-java-project-V1.jar  # Adjusted to the correct JAR file name

    - name: Run Unit Test
      run: gradle test

    - name: Upload Test Reports
      uses: actions/upload-artifact@v3
      with:
        name: test-reports
        path: build/reports/tests/test/*

    - name: Generate code coverage report
      run: gradle jacocoTestReport

    - name: Upload code coverage report
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: build/reports/jacoco/test/html/**

   - name: Build Docker image  

    run: docker build -t sample-java-project .  

   - name: Run Docker container  

   run: docker run -d -p 8080:8080 --name sample-java-project-container sample-java-project  

   - name: Verify Docker container is running  

   run: | docker ps 
